# Generated by Django 5.1.1 on 2024-09-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.PositiveIntegerField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Fail', 'Fail')], max_length=50)),
                ('source', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.PositiveIntegerField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=7)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Fail', 'Fail')], max_length=50)),
                ('source', models.CharField(max_length=50)),
            ],
        ),
    ]
