# Generated by Django 5.1.1 on 2024-09-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='femployee',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Updated', 'Updated')], max_length=50),
        ),
        migrations.AlterField(
            model_name='semployee',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Updated', 'Updated')], max_length=50),
        ),
    ]
