# Generated by Django 5.1.1 on 2024-09-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_femployee_status_alter_semployee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='femployee',
            name='designation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='femployee',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='semployee',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='semployee',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
