# Generated by Django 5.1.1 on 2024-09-30 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_femployee_designation_alter_femployee_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failure', 'Failure')], default='Failure', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='femployee',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Updated', 'Updated')], default='Created', max_length=50),
        ),
        migrations.AlterField(
            model_name='semployee',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Updated', 'Updated')], default='Created', max_length=50),
        ),
        migrations.AlterField(
            model_name='femployee',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employee.job'),
        ),
        migrations.AlterField(
            model_name='semployee',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.job'),
        ),
    ]
