# Generated by Django 5.1.1 on 2024-09-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_semployee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semployee',
            name='salary',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
