# Generated by Django 5.1.1 on 2024-10-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_semployee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semployee',
            name='salary',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
