# Generated by Django 5.1.1 on 2024-10-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_semployee_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='femployee',
            name='source',
        ),
        migrations.AlterField(
            model_name='semployee',
            name='salary',
            field=models.FloatField(default=0.0),
        ),
        migrations.RemoveField(
            model_name='semployee',
            name='source',
        ),
        migrations.AddField(
            model_name='femployee',
            name='source',
            field=models.ManyToManyField(related_name='femployees', to='employee.job'),
        ),
        migrations.AddField(
            model_name='semployee',
            name='source',
            field=models.ManyToManyField(related_name='semployees', to='employee.job'),
        ),
    ]
