# Generated by Django 5.1.1 on 2024-10-03 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_remove_femployee_source_alter_semployee_salary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='femployee',
            old_name='source',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='semployee',
            old_name='source',
            new_name='job',
        ),
    ]
