# Generated by Django 5.1.1 on 2024-10-03 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_rename_source_femployee_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semployee',
            name='designation',
        ),
    ]
