# Generated by Django 5.1.1 on 2024-10-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_remove_semployee_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='femployee',
            name='job',
        ),
        migrations.RemoveField(
            model_name='semployee',
            name='job',
        ),
        migrations.AddField(
            model_name='femployee',
            name='job',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='semployee',
            name='job',
            field=models.CharField(default='', max_length=200),
        ),
    ]
